"""Add deleted column to File model

Revision ID: 35a17de72c98
Revises: 6cd7fb4950e1
Create Date: 2024-03-13 17:23:29.260187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a17de72c98'
down_revision = '6cd7fb4950e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
