"""Add timestamp column to File model

Revision ID: 6cd7fb4950e1
Revises: 702db8248234
Create Date: 2024-03-13 17:12:32.339172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd7fb4950e1'
down_revision = '702db8248234'
branch_labels = None
depends_on = None

def upgrade():
    # Existing code...

    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_activity_log')
    op.add_column('file', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_file_user_id', 'file', 'user', ['user_id'], ['id'])

    # Existing code...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('directory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    op.create_table('user_activity_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_usage')
    # ### end Alembic commands ###
