from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '9adffa2cc01e'
down_revision = '1bb26c85e42e'
branch_labels = None
depends_on = None

def upgrade():
    # Other migration operations
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('size')
    # ### end Alembic commands ###
